### ISSUE TITLE
Absolute path in config file

### ISSUE THREAD

**Issue by Furrior** [IamGreyWolf/GreysESOReshadePreset#1]
ReShade.ini contain two absolute paths: `IntermediateCachePath`, `PresetPath`. While the first doesnt break anything(as far as I noticed), if the latter doesnt match the actual eso path, reshade just doesnt work.
Solution(Would do it myself, but your way to store things in an archive is really unhandy for contributing quickly): change default `PresetPath` to `.\Grey.ini`, change `IntermediateCachePath` to `%Temp%`

**Comment by IamGreyWolf** [comment]
@Furrior thanks. I will look into the files. I am new to Github and this kind of sharing of files. What would you suggest how should I store this here? Just the Repo without a zip file? I thought it would make things easier for users.
I'm open for any advice.

**Comment by Furrior** [comment]
> @Furrior thanks. I will look into the files. I am new to Github and this kind of sharing of files. What would you suggest how should I store this here? Just the Repo without a zip file? I thought it would make things easier for users.
> I'm open for any advice.

Its indeed easier for users, but GitHub is mainly used for storing source code/files that use git. Git doesn't make much sense for binary files(including achives)((There are special tools for this, but they still arent good for tracking changes history what is the main purpose of git). If I were you, I would make final archives for end users as releases(google github releases) or just said to use 'download as zip' button, but it would contain a readme file and screenshots.

**Comment by IamGreyWolf** [comment]
@Furrior thanks again. Learning a lot !
I deleted the zip file and updated the repo with updated reshade.ini file and apart from that only needed reshade files and comparison screenshots. I will advise people to use the download ZIP button.
